if(NOT curl_FOUND)
    check_init_submodule(${PROJECT_SOURCE_DIR}/thirdparty/curl)

    set(BUILD_CURL_EXE OFF)
    set(BUILD_SHARED_LIBS OFF)
    set(BUILD_STATIC_LIBS ON)
    set(CURL_DISABLE_INSTALL ON)
    set(ENABLE_UNICODE ON)
    set(HTTP_ONLY ON)
    set(ENABLE_WEBSOCKETS ON)
    set(CURL_DISABLE_NTLM ON)
    set(BUILD_LIBCURL_DOCS OFF)
    set(BUILD_MISC_DOCS OFF)
    set(ENABLE_CURL_MANUAL OFF)
    set(CURL_USE_SCHANNEL ON)
    set(CURL_USE_OPENSSL OFF)
    set(USE_NGHTTP2 OFF)
    set(USE_NGTCP2 OFF)
    set(USE_QUICHE OFF)
    set(USE_MSH3 OFF)
    set(USE_OPENSSL_QUIC OFF)
    set(USE_LIBIDN2 OFF)
    set(USE_WIN32_IDN ON)
    set(CURL_USE_LIBPSL OFF)
    set(CURL_USE_LIBSSH2 OFF)
    set(CURL_CA_BUNDLE "none")
    set(CURL_CA_PATH "none")

    add_subdirectory(${PROJECT_SOURCE_DIR}/thirdparty/curl curl)
    set(curl_FOUND
        1
        PARENT_SCOPE
        )
endif()
